spring:
  application:
    name: FirstProject
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/first_project
    username: root
    password: green502

  servlet:
    multipart:
      max-file-size: 10MB #?? ?? ??
      max-request-size: 30MB
logging:
  level:
    root: info
mybatis:
  mapper-locations: mappers/**/*.xml
Springdoc:
  api-docs:

    version: openapi_3_1
    #swagger ui ??
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    cache:
      disabled: true

file:
  directory: D:\2024-01\download\firstproject\

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.0.144:3306/db_odd_first_4
    username: odd_first_4
    password: cell
file:
  directory: /home/download/

